# Generated by Django 5.1.3 on 2024-11-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(
                        db_index=True, max_length=512, unique=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=8, max_digits=32),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=32)),
                ("executed_date", models.DateTimeField()),
                ("side", models.BooleanField()),
                ("instrument", models.CharField(max_length=16)),
                (
                    "fees_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_currencies",
                        to="common.currency",
                    ),
                ),
                (
                    "counter_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_currencies",
                        to="common.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.entity",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.exchange",
                    ),
                ),
                (
                    "fees_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees_currencies",
                        to="common.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=8, max_digits=32),
                ),
                (
                    "leg_type",
                    models.CharField(
                        choices=[
                            ("Fees", "FEES"),
                            ("Base", "BASE"),
                            ("Counter", "COUNTER"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.currency",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.exchange",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.trade",
                    ),
                ),
            ],
        ),
    ]
