LENGTH_EXCHANGE_NAME = 128

# Trades
LENGTH_TRADE_ID = 512
LENGTH_INSTRUMENT = 16

# Price/Quantity
TRADE_MAX_DIGITS_PRICE = 32
TRADE_MAX_DIGITS_QUANTITY = 32
TRADE_MAX_DIGITS_FEES_QUANTITY = 32

# Trade
TRADE_DECIMAL_PLACES_PRICE = 8
TRADE_DECIMAL_PLACES_QUANTITY = 8
TRADE_DECIMAL_PLACES_FEES_QUANTITY = 8

# Ledger leg

LEDGER_LEG_MAX_DIGITS = 32
LEDGER_LEG_DECIMAL_PLACES = 18
LEDGER_LEG_FEE_MAX_DIGITS = 32
LEDGER_LEG_FEE_DECIMAL_PLACES = 18
LEDGER_LEG_DESCRIPTION_LENGTH = 256
