name: 'Setup Python and Poetry'
description: 'Set up Python and Poetry with caching'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.13'
  poetry-version:
    description: 'Poetry version'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Cache Poetry virtual environment
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Install Dependencies
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry install