name: 'Setup Development Tools'
description: 'Set up hadolint, shellcheck, and prettier'

runs:
  using: 'composite'
  steps:
    - name: Install hadolint
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install hadolint
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
        fi

    - name: Install shellcheck
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y shellcheck
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install shellcheck
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
        fi

    - name: Setup Node.js for prettier
      uses: actions/setup-node@v4
      with:
        node-version: '20'