version: '3.8'

services:
  redis:
    image: redis:8.0
    container_name: puzzle-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7.10
    container_name: puzzle-influxdb
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-puzzlepuzzle}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-puzzlepuzzle}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-badaas}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-puzzlepuzzle}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-puzzlepuzzle}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: puzzle-postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-puzzle}
      - POSTGRES_USER=${DB_USER:-puzzle}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-puzzlepuzzle42}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  puzzle:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: puzzle-app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_NAME=${DB_NAME:-puzzle}
      - DB_USER=${DB_USER:-puzzle}
      - DB_PASSWORD=${DB_PASSWORD:-puzzlepuzzle42}
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-puzzlepuzzle}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-badaas}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-puzzlepuzzle}
      - SECRET_KEY=${SECRET_KEY:-verysecret}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    depends_on:
      - redis
      - influxdb
      - postgres
    restart: unless-stopped

volumes:
  redis-data:
  influxdb-data:
  influxdb-config:
  postgres-data: