name: Build

on:
  workflow_run:
    workflows: ["Lint and Format", "Test"]
    types:
      - completed
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: make docker-build
