name: Lint and Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04, macos-latest]
        python-version: ["3.13"]
        poetry-version: ["latest"]
        include:
          - os: ubuntu-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install hadolint
      run: |
        sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        sudo chmod +x /usr/local/bin/hadolint
      shell: bash

    - name: Install shellcheck
      run: |
        sudo apt-get update && sudo apt-get install -y shellcheck
      shell: bash

    - name: Setup Node.js for prettier
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install Dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry install

    - name: Run linting checks
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make lint

    - name: Run formatting checks
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make format-check

    - name: Check trailing whitespaces
      run: make check-trailing-whitespace

    - name: Lint Dockerfiles
      run: make lint-dockerfiles

    - name: Lint shell scripts
      run: make lint-bash

    - name: Check markdown formatting
      run: make check-md