name: Lint and Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04, macos-latest]
        python-version: ["3.13"]
        poetry-version: ["latest"]
        include:
          - os: ubuntu-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python and Poetry
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
        poetry-version: ${{ matrix.poetry-version }}

    - name: Setup Development Tools
      uses: ./.github/actions/setup-tools

    - name: Run linting checks
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make lint

    - name: Run formatting checks
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make format-check

    - name: Check trailing whitespaces
      run: make check-trailing-whitespace

    - name: Lint Dockerfiles
      run: make lint-dockerfiles

    - name: Lint shell scripts
      run: make lint-bash

    - name: Check markdown formatting
      run: make check-md